### ISSUE TITLE
Support for registering ItemCollection into the EOEPCA catalogue

### ISSUE THREAD

**Issue by spinto** [EOEPCA/eoepca-plus#39]
It is possible to register a full STAC catalogue using the harvester, but if platform providers just need a simple publishing of STAC items in bulk currently they need to POST one-by-one a STAC to the catalogue (at least for pyCSW, I am unsure about EOAPI)

The STAC transaction extension ( https://github.com/stac-api-extensions/transaction ) offers the possibility to POST an ItemCollection, which is a GeoJSON FeatureCollection containing an array of features to be ingested.

It would help to implement this behavior also in pyCSW (and potentially also in EOAPI), and then in the OGC API Records in the future.

NOTE: This could help also make faster the harvester registration, as the harvester could post to the catalogue data in bulk.

**Comment by kalxas** [comment]
Thank you @spinto 
I have linked this issue with the transaction issue in Resource Discovery BB

**Comment by kalxas** [comment]
During our last resource discovery meeting we also identified this needs to be added in eoAPI STAC implementation

**Comment by kalxas** [comment]
This has been implemented in https://github.com/geopython/pycsw/pull/1054
